# Docker Compose file for development settings. Extends the base docker-compose.yaml file.
# Sets volumes for live code updates, and environment variables.

services:
  mongodb:

  app:
    build:
      dockerfile: Dockerfile.development
      
    # Mount the source to '/usr/src/app/src' in the container to allow for live code updates.
    # Mount the 'node_modules' directory in the container to avoid conflicts with the host.
    volumes:
      - ./src/:/app/src
      - ./public/:/app/public
      - ./logs:/app/logs
      - /app/node_modules
    
